### ISSUE TITLE
Multiple Authentication Types

### ISSUE THREAD

**Issue by ibovyrin** [hh-h/aiohttp-swagger3#23]
Hi @hh-h ,

Thank you for great lib!

I found and issue with auth types. Currently on some routes we have to use `bearer` or `cookie`  auth for different types of request. They configured for routes in a following way:

>     security:
>       - bearerAuth: []
>       - cookieAuth: []

However, when client sends both header and cookie it receives an error:
https://github.com/hh-h/aiohttp-swagger3/blob/master/aiohttp_swagger3/validators.py#L541

Documentation for swagger states that any of auth mechanisms should be provided.
Is it possible to have them both enabled and set priority by sequence in `security` list?

**Comment by hh-h** [comment]
Nope, that's a specification, see `Using Multiple Authentication Types` here: https://swagger.io/docs/specification/authentication/

**Comment by hh-h** [comment]
try this
```
- A
   B
- A
- B
```

**Comment by hh-h** [comment]
@ibovyrin Thank you for your interest in the library. After rereading the specification, I understood that it is better to use `anyOf` instead of `oneOf` because the example above also does not work, it generates the same error: `oneOf`. The fix is already available in the open test PR and I will add it to the main branch soon.

**Comment by hh-h** [comment]
https://github.com/hh-h/aiohttp-swagger3/pull/25

**Comment by ibovyrin** [comment]
Thank you @hh-h !
