### ISSUE TITLE
Support for route decorators?

### ISSUE THREAD

**Issue by charleswhchan** [hh-h/aiohttp-swagger3#8]
Currently, to use aiohttp-swagger3, one needs to use SwaggerDocs.add_routes():

```
    s = SwaggerDocs(app, '/docs', title="Swagger Petstore", version="1.0.0", components="components.yaml")
    s.add_routes([
        web.get("/pets/{pet_id}", get_one_pet),
    ])
```

Is it possible to use aiohttp decorator format?
```
routes = web.RouteTableDef()

@routes.get('/')
async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes(routes)
web.run_app(app)
```

A example in my mind is like what aiohttp-swagger, where you can define the app the way you want, then add `setup_swagger(app)`. That style is more easily to adapt the existing code base. (https://aiohttp-swagger.readthedocs.io/en/latest/quick_start.html):
```
from aiohttp import web
from aiohttp_swagger import *


async def ping(request):
    """
    ---
    description: This end-point allow to test that service is up.
    tags:
    - Health check
    produces:
    - text/plain
    responses:
        "200":
            description: successful operation. Return "pong" text
        "405":
            description: invalid HTTP Method
    """
    return web.Response(text="pong")


app = web.Application()
app.router.add_route('GET', "/ping", ping)

setup_swagger(app)

web.run_app(app, host="127.0.0.1")
```

Is this something that can be added easily?

**Comment by hh-h** [comment]
Hello, yes it is supported, see example in tests https://github.com/hh-h/aiohttp-swagger3/blob/master/tests/tests.py#L2872
It that what you're looking for?

Regarging `setup_swagger` function, unfortunately, I don't know easy way to achieve that. aiohttp-swagger doesn't support validation, so it's just proxy routes to router and add two more routes for swagger. aiohttp-apiset works in different way, it uses custom router, but this is deprecated and will be deleted in aiohttp 4. I tried to design this library so that it supports all versions of aiohttp.

Anyway, it should be easy to modify your code base, create `RouteTableDef` somewhere, fill it with handlers and pass instance to `SwaggerDocs` instead of `Application`.

**Comment by charleswhchan** [comment]
Thanks @hh-h. That's exactly what I am looking for. 

I created PR #10 to include an example for route decorator in README.
